# Lackluster theme for kitty

foreground #DDDDDD
background #0A0A0A

cursor #DDDDDD
cursor_trail_color #DDDDDD

color0 #080808
color8 #444444

color1 #D70000
color9 #D70000

color2 #789978
color10 #789978

color3 #ffAA88
color11 #ffAA88

color4 #7788AA
color12 #7788AA

# changed magenta from default
color5 #9D449D
color13 #9D449D

# Cyan is set to lack
color6 #708090
color14 #708090

# White is set to luster
color7 #DDDDDD
color15 #DDDDDD

# Cursor
cursor #DDDDDD
cursor_text_color #080808

# Border colors
active_border_color #D70000
inactive_border_color #7A7A7A

# Tab bar colors
active_tab_foreground #CCCCCC
active_tab_background #444444
inactive_tab_foreground #7A7A7A
inactive_tab_background #191919

tab_bar_edge top
tab_bar_style separator
tab_separator " ╏ "

# Selection highlight
selection_foreground #191919
selection_background #CCCCCC

# The color for highlighting URLs on mouse-over
url_color #D7007D
