#: Kitty Keybinds
#
# Unbind conflicting keybinds
map ctrl+shift+n no_op

map kitty_mod+] next_tab
map kitty_mod+[ prev_tab

map kitty_mod+p show_scrollback
map kitty_mod+g launch --type=overlay lkitty
map kitty_mod+y launch --type=tab lkitty -e

# Replacement keybinds
map kitty_mod+enter launch --type=window --cwd=current
