#: Kitty Keybinds
#
map kitty_mod+] next_tab
map kitty_mod+[ prev_tab

map kitty_mod+n next_window
map kitty_mod+p prev_window

map kitty_mod+/  show_scrollback

map kitty_mod+g launch --type=tab lkitty
map kitty_mod+y launch --type=tab lkitty -e

map kitty_mod+; next_layout

# Replacement keybinds
map kitty_mod+enter launch --type=window --cwd=current
