# kitty.conf

## Settings
 
### Font
font_family Go Mono 
font_size 11

### Cursor
cursor_trail 1
cursor_trail_decay 0.05 0.1

background_blur 1
background_opacity 0.8

enable_audio_bell no
allow_remote_control yes

### Scrollback
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist number relativenumber' +'$' -

pixel_scroll yes


### Mappings
include keybinds.conf

### Layouts 
enabled_layouts tall:bias=60;full_size=1;mirred=false,stack

# BEGIN_KITTY_THEME
# Flexoki (Dark)
include current-theme.conf
# END_KITTY_THEME

include nerd-fix.conf
