#!/bin/bash

d=$(find $HOME -type d | fzf )
[[ -z $d ]] && exit 1
if [ ! $(tmux attach -t $(basename $d)) ]
then
	tmux new-session -s $(basename $d) -d -c $d 
	tmux new-window -t $(basename $d) -c $d nvim .
	tmux attach-session  -t $(basename $d)
fi
echo $d

