#!/bin/bash

f=$(find $HOME -type f | fzf)                                                                                                                                                                       
if [ ! -z $f ]; then
	nvim $f
	echo $f
fi
