#!/bin/bash

f=$(find $HOME -type f | fzf)                                                                                                                                                                       
[[ -z $f ]] && exit 1
nvim $f
echo $f

