# .tmux.conf

# rebind prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind -n C-Space send-prefix

bind r source-file ~/.tmux.conf \; display "Reloaded!" # quick reload

set-option -sg escape-time 10

# scrollback keybinds
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g status-fg "#dddddd"
set -g status-bg "#444444"
set -g message-style bg=red,fg=white

# options for the image plugin in nvim
set -gq allow-passthrough on
set -g visual-activity off

